# Generated by Django 3.1.4 on 2020-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
