# Generated by Django 3.1.4 on 2020-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0002_url_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
