# Generated by Django 3.1.4 on 2020-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0003_auto_20201224_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='interval',
            field=models.IntegerField(default=30),
        ),
    ]
